name: Build RC
on:
  workflow_dispatch:
    inputs:
      flavor:
        type: choice
        description: 'Flavor'
        required: true
        options:
          - Generic
          - Boost
          - Tmobile
      versionName:
        description: 'Version Number'
        required: true
      Singing:
        type: choice
        description: 'Choose Singing option'
        required: true
        options:
          - Sign
          - Unsign
          - Sign And Unsign
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called “greet”
  buildRC:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo “Hello ${{ github.event.inputs.flavor }}”
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create Release Branch
        run: git checkout -b release/v${{ github.event.inputs.versionName }}
      - name: Push new branch
        run: git push origin release/v${{ github.event.inputs.versionName }}
#      - name: buildTmo
#        run: ./gradlew app:assembleTmobileProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Metrozone’}}
#
#      - name: buildGeneric
#        run: ./gradlew app:assembleGenericProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Generic’}}
#
#      - name: buildBoost
#        run: ./gradlew app:assembleBoostProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Boost’}}
#      - name : printVersion
#        run: ./gradlew -q printVersionName
