name: Build RC
on:
  workflow_dispatch:
    inputs:
      Flavor:
        type: choice
        description: 'Flavor'
        required: true
        options:
          - Generic
          - Boost
          - Tmobile
      Singing:
        type: choice
        description: 'Choose Singing option'
        required: true
        options:
          - Sign
          - Unsign
          - Sign And Unsign
      Version_Number:
        description: 'Version Number'
        required: true

jobs:
  buildRC:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Echo flavor
        run: echo “Hello ${{ github.event.inputs.Flavor }}”
      - name: Echo Singing
        run: echo “Hello ${{ github.event.inputs.Singing }}”
      - name: Echo Version number
        run: echo “Hello ${{ github.event.inputs.Version_Number }}”


#      - name: Checkout the code
#        uses: actions/checkout@v2
#      - name: buildTmo
#        run: ./gradlew app:assembleTmobileProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Metrozone’}}
#
#      - name: buildGeneric
#        run: ./gradlew app:assembleGenericProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Generic’}}
#
#      - name: buildBoost
#        run: ./gradlew app:assembleBoostProductionRelease
#        if: ${{github.event.inputs.flavor == ‘Boost’}}
#      - name : printVersion
#        run: ./gradlew -q printVersionName
